server:
  port: 18008
spring:
  datasource:
    # db 文件路径
    db-file: db/book-meeting.sqlite3
    url: jdbc:sqlite:${spring.datasource.db-file}
    driver-class-name: org.sqlite.JDBC
    # 无用户名密码
    username:
    password: